return
{
    configurationEnableWindow = false,
    enable = true,
    printItemIndex = true,
    showItemIDs = false,
    showItemData = false,
    showEquippedItems = true,
    shortPBNames = true,
    ignoreMeseta = true,
    invertItemList = true,
    hideMagStats = true,
    hideMagPBs = false,
    itemNameLength = 0,
    server = 1,
    updateThrottle = 0,
    aio = {
        EnableWindow = true,
        Anchor = 1,
        X = 50,
        Y = 50,
        W = 450,
        H = 350,
        NoTitleBar = "",
        NoResize = "",
        NoMove = "",
        AlwaysAutoResize = "AlwaysAutoResize",
        TransparentWindow = false,
        ShowButtonSaveToFile = true,
        SelectedInventory = 1,
    },
    floor = {
        EnableWindow = true,
        Anchor = 1,
        X = 50,
        Y = 50,
        W = 450,
        H = 350,
        NoTitleBar = "NoTitleBar",
        NoResize = "",
        NoMove = "",
        AlwaysAutoResize = "AlwaysAutoResize",
        TransparentWindow = false,
    },
    mags = {
        EnableWindow = true,
        Anchor = 1,
        X = 50,
        Y = 50,
        W = 450,
        H = 350,
        NoTitleBar = "NoTitleBar",
        NoResize = "",
        NoMove = "",
        AlwaysAutoResize = "AlwaysAutoResize",
        TransparentWindow = false,
    },
}
